apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
  labels:
    app: backend
    team: platform
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
