apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - namespace.yaml
  - frontend/serviceaccount.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - frontend/pdb.yaml
  - backend/serviceaccount.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - backend/pdb.yaml
  - redis/deployment.yaml
  - redis/service.yaml

commonLabels:
  app.kubernetes.io/part-of: infragpt
  app.kubernetes.io/managed-by: argocd
