apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-engine-models
  namespace: ai-engine
  labels:
    app: ai-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
